Enhavo\Bundle\ArticleBundle\Entity\Article:
    properties:
        title:
            - Plain:
                weight: 30
                type: title
        teaser:
            - Plain:
                weight: 25
                type: teaser
        grid:
            - Model
