Enhavo\Bundle\GridBundle\Entity\Grid:
    properties:
        items:
            - Collection:
                entity: Enhavo\Bundle\GridBundle\Entity\Item

Enhavo\Bundle\GridBundle\Entity\Item:
    properties:
        itemType:
            - Model

Enhavo\Bundle\GridBundle\Entity\CiteText:
    properties:
       cite:
            - Plain:
                weight: 15
                type: citeText

Enhavo\Bundle\GridBundle\Entity\Picture:
    properties:
       title:
            - Plain:
                weight: 25
                type: title
       caption:
            - Plain:
                weight: 5
                type: caption

Enhavo\Bundle\GridBundle\Entity\PicturePicture:
    properties:
       title:
            - Plain:
                weight: 25
                type: title
       captionLeft:
            - Plain:
                weight: 5
                type: caption
       captionRight:
            - Plain:
                weight: 5
                type: caption

Enhavo\Bundle\GridBundle\Entity\Text:
    properties:
       title:
            - Plain:
                weight: 25
                type: title
       text:
            - Html:
                weights:
                  h1: 25
                  h2: 18
                  p: 15
                type: text

Enhavo\Bundle\GridBundle\Entity\TextPicture:
    properties:
       title:
            - Plain:
                weight: 25
                type: title
       text:
            - Html:
                type: text

Enhavo\Bundle\GridBundle\Entity\TextText:
    properties:
        title:
            - Plain:
                weight: 25
                type: title
        titleLeft:
            - Plain:
                weight: 18
                type: title
        textLeft:
            - Html:
                type: text
        titleRight:
            - Plain:
                weight: 18
                type: title
        textRight:
            - Html:
                type: text

Enhavo\Bundle\GridBundle\Entity\Video:
    properties:
        title:
            - Plain:
                weight: 20
                type: title
